import { createApi } from "@reduxjs/toolkit/query/react";
import { customFetchBaseQuery } from "../baseQuery";

// Define the API slice
export const userApi = createApi({
  reducerPath: "userApi", // Unique name for the API slice
  baseQuery: customFetchBaseQuery(),
  tagTypes: ["User"], // Define the tag type for caching
  endpoints: (builder) => ({
    updateProfile: builder.mutation({
      query: (data) => ({
        url: `/auth/settings`,
        method: "PUT",
        body:data
      }),
      invalidatesTags: ["User"],
    }),
    getProfile: builder.query({ 
      query: () => `/auth/profile`, 
      transformResponse: (res) => res.data,
      providesTags: ["User"],
    }),

  
    
  }),
});

// Export hooks generated by RTK Query
export const { useUpdateProfileMutation,useGetProfileQuery } = userApi;
