import { createApi } from "@reduxjs/toolkit/query/react";
import { customFetchBaseQuery } from "../baseQuery";

// Define the API slice
export const userApi = createApi({
  reducerPath: "userApi", // Unique name for the API slice
  baseQuery: customFetchBaseQuery(),
  tagTypes: ["User"], // Define the tag type for caching
  endpoints: (builder) => ({
    updateProfile: builder.mutation({
      query: (data) => ({
        url: `/auth/settings`,
        method: "PUT",
        body: data
      }),
      invalidatesTags: ["User"],
    }),
    getProfile: builder.query({
      query: () => `/auth/profile`,
      transformResponse: (res) => res.data,
      providesTags: ["User"],
    }),
    logoutAccount: builder.mutation({
      query: () => ({
        url: `/auth/logout`,
        method: "POST",
      }),
      invalidatesTags: ["User"],
    }),
    getAllUsers: builder.query({
      query: ({ page, limit, search,role }) => {
        let url = `/admin/app/users?page=${page}`
        if (limit) {
          url += `&limit=${limit}`
        }
        if (search) {
          url += `&search=${search}`
        }
        if(role){
          url += `&role=${role}`
        }
        return url
      },
      providesTags: ["User"],
    }),
    updateUserStatus: builder.mutation({
      query: ({ id, status }) => ({
        url: `/admin/auth/update_user/${id}`,
        method: "PUT",
        body: { status }
      }),
      invalidatesTags: ["User"],
    }),
  }),
});

// Export hooks generated by RTK Query
export const { useUpdateProfileMutation, useGetProfileQuery, useLogoutAccountMutation , useGetAllUsersQuery, useUpdateUserStatusMutation } = userApi;
